
import Cursor from '@/components/cursor'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'

const poppins = Poppins({ subsets: ['latin'] ,weight: ['400', '500','600']})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>

      <body className={poppins.className}>

        <ThemeProvider 
        attribute='class'
        defaultTheme='dark'
        enableSystem
        storageKey='portfolio-m'
        >
          <Cursor />
          <div className=' dark:bg-[#060608] h-screen w-full '>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  )
}
